### ISSUE TITLE
Does not take into account that the user might disallow an application.

### ISSUE THREAD

**Issue by freak3dot** [btimby/fs-dropbox#6]
https://www.dropbox.com/developers/core/bestpractices:

```
In the case where a token is no longer authorized, the REST API will return an HTTP Error 401 Unauthorized response.
```

This library does not handle the 401 in the dropbox.rest.ErrorResponse.

**Comment by btimby** [comment]
The library can do nothing about this error so it correctly allows it to
unroll the stack. Higher level apps should handle this error.
